// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RGMessages.proto

package io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg;

public final class RGMessages {
  private RGMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ListRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.protocol.resource.ListRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKey schemaToken = 1;</code>
     */
    boolean hasSchemaToken();
    /**
     * <code>optional .io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKey schemaToken = 1;</code>
     */
    io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey getSchemaToken();
    /**
     * <code>optional .io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKey schemaToken = 1;</code>
     */
    io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKeyOrBuilder getSchemaTokenOrBuilder();

    /**
     * <code>optional int32 maxEntries = 2;</code>
     */
    boolean hasMaxEntries();
    /**
     * <code>optional int32 maxEntries = 2;</code>
     */
    int getMaxEntries();

    /**
     * <code>optional bool includeDeleted = 3 [default = false];</code>
     */
    boolean hasIncludeDeleted();
    /**
     * <code>optional bool includeDeleted = 3 [default = false];</code>
     */
    boolean getIncludeDeleted();
  }
  /**
   * Protobuf type {@code io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.protocol.resource.ListRequest}
   */
  public static final class ListRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.protocol.resource.ListRequest)
      ListRequestOrBuilder {
    // Use ListRequest.newBuilder() to construct.
    private ListRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ListRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ListRequest defaultInstance;
    public static ListRequest getDefaultInstance() {
      return defaultInstance;
    }

    public ListRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ListRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = schemaToken_.toBuilder();
              }
              schemaToken_ = input.readMessage(io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(schemaToken_);
                schemaToken_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              maxEntries_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              includeDeleted_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.internal_static_io_pravega_segmentstore_storage_impl_chunkstream_storageos_data_protocol_resource_ListRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.internal_static_io_pravega_segmentstore_storage_impl_chunkstream_storageos_data_protocol_resource_ListRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListRequest.class, io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<ListRequest> PARSER =
        new com.google.protobuf.AbstractParser<ListRequest>() {
      public ListRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ListRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ListRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SCHEMATOKEN_FIELD_NUMBER = 1;
    private io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey schemaToken_;
    /**
     * <code>optional .io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKey schemaToken = 1;</code>
     */
    public boolean hasSchemaToken() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKey schemaToken = 1;</code>
     */
    public io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey getSchemaToken() {
      return schemaToken_;
    }
    /**
     * <code>optional .io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKey schemaToken = 1;</code>
     */
    public io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKeyOrBuilder getSchemaTokenOrBuilder() {
      return schemaToken_;
    }

    public static final int MAXENTRIES_FIELD_NUMBER = 2;
    private int maxEntries_;
    /**
     * <code>optional int32 maxEntries = 2;</code>
     */
    public boolean hasMaxEntries() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 maxEntries = 2;</code>
     */
    public int getMaxEntries() {
      return maxEntries_;
    }

    public static final int INCLUDEDELETED_FIELD_NUMBER = 3;
    private boolean includeDeleted_;
    /**
     * <code>optional bool includeDeleted = 3 [default = false];</code>
     */
    public boolean hasIncludeDeleted() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool includeDeleted = 3 [default = false];</code>
     */
    public boolean getIncludeDeleted() {
      return includeDeleted_;
    }

    private void initFields() {
      schemaToken_ = io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey.getDefaultInstance();
      maxEntries_ = 0;
      includeDeleted_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasSchemaToken()) {
        if (!getSchemaToken().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, schemaToken_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, maxEntries_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, includeDeleted_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, schemaToken_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, maxEntries_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, includeDeleted_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.protocol.resource.ListRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.protocol.resource.ListRequest)
        io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.internal_static_io_pravega_segmentstore_storage_impl_chunkstream_storageos_data_protocol_resource_ListRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.internal_static_io_pravega_segmentstore_storage_impl_chunkstream_storageos_data_protocol_resource_ListRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListRequest.class, io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListRequest.Builder.class);
      }

      // Construct using io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSchemaTokenFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (schemaTokenBuilder_ == null) {
          schemaToken_ = io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey.getDefaultInstance();
        } else {
          schemaTokenBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        maxEntries_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        includeDeleted_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.internal_static_io_pravega_segmentstore_storage_impl_chunkstream_storageos_data_protocol_resource_ListRequest_descriptor;
      }

      public io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListRequest getDefaultInstanceForType() {
        return io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListRequest.getDefaultInstance();
      }

      public io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListRequest build() {
        io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListRequest buildPartial() {
        io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListRequest result = new io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (schemaTokenBuilder_ == null) {
          result.schemaToken_ = schemaToken_;
        } else {
          result.schemaToken_ = schemaTokenBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.maxEntries_ = maxEntries_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.includeDeleted_ = includeDeleted_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListRequest) {
          return mergeFrom((io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListRequest other) {
        if (other == io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListRequest.getDefaultInstance()) return this;
        if (other.hasSchemaToken()) {
          mergeSchemaToken(other.getSchemaToken());
        }
        if (other.hasMaxEntries()) {
          setMaxEntries(other.getMaxEntries());
        }
        if (other.hasIncludeDeleted()) {
          setIncludeDeleted(other.getIncludeDeleted());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasSchemaToken()) {
          if (!getSchemaToken().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey schemaToken_ = io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey, io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey.Builder, io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKeyOrBuilder> schemaTokenBuilder_;
      /**
       * <code>optional .io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKey schemaToken = 1;</code>
       */
      public boolean hasSchemaToken() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKey schemaToken = 1;</code>
       */
      public io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey getSchemaToken() {
        if (schemaTokenBuilder_ == null) {
          return schemaToken_;
        } else {
          return schemaTokenBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKey schemaToken = 1;</code>
       */
      public Builder setSchemaToken(io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey value) {
        if (schemaTokenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          schemaToken_ = value;
          onChanged();
        } else {
          schemaTokenBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKey schemaToken = 1;</code>
       */
      public Builder setSchemaToken(
          io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey.Builder builderForValue) {
        if (schemaTokenBuilder_ == null) {
          schemaToken_ = builderForValue.build();
          onChanged();
        } else {
          schemaTokenBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKey schemaToken = 1;</code>
       */
      public Builder mergeSchemaToken(io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey value) {
        if (schemaTokenBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              schemaToken_ != io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey.getDefaultInstance()) {
            schemaToken_ =
              io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey.newBuilder(schemaToken_).mergeFrom(value).buildPartial();
          } else {
            schemaToken_ = value;
          }
          onChanged();
        } else {
          schemaTokenBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKey schemaToken = 1;</code>
       */
      public Builder clearSchemaToken() {
        if (schemaTokenBuilder_ == null) {
          schemaToken_ = io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey.getDefaultInstance();
          onChanged();
        } else {
          schemaTokenBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKey schemaToken = 1;</code>
       */
      public io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey.Builder getSchemaTokenBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getSchemaTokenFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKey schemaToken = 1;</code>
       */
      public io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKeyOrBuilder getSchemaTokenOrBuilder() {
        if (schemaTokenBuilder_ != null) {
          return schemaTokenBuilder_.getMessageOrBuilder();
        } else {
          return schemaToken_;
        }
      }
      /**
       * <code>optional .io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKey schemaToken = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey, io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey.Builder, io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKeyOrBuilder> 
          getSchemaTokenFieldBuilder() {
        if (schemaTokenBuilder_ == null) {
          schemaTokenBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey, io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey.Builder, io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKeyOrBuilder>(
                  getSchemaToken(),
                  getParentForChildren(),
                  isClean());
          schemaToken_ = null;
        }
        return schemaTokenBuilder_;
      }

      private int maxEntries_ ;
      /**
       * <code>optional int32 maxEntries = 2;</code>
       */
      public boolean hasMaxEntries() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 maxEntries = 2;</code>
       */
      public int getMaxEntries() {
        return maxEntries_;
      }
      /**
       * <code>optional int32 maxEntries = 2;</code>
       */
      public Builder setMaxEntries(int value) {
        bitField0_ |= 0x00000002;
        maxEntries_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 maxEntries = 2;</code>
       */
      public Builder clearMaxEntries() {
        bitField0_ = (bitField0_ & ~0x00000002);
        maxEntries_ = 0;
        onChanged();
        return this;
      }

      private boolean includeDeleted_ ;
      /**
       * <code>optional bool includeDeleted = 3 [default = false];</code>
       */
      public boolean hasIncludeDeleted() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bool includeDeleted = 3 [default = false];</code>
       */
      public boolean getIncludeDeleted() {
        return includeDeleted_;
      }
      /**
       * <code>optional bool includeDeleted = 3 [default = false];</code>
       */
      public Builder setIncludeDeleted(boolean value) {
        bitField0_ |= 0x00000004;
        includeDeleted_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool includeDeleted = 3 [default = false];</code>
       */
      public Builder clearIncludeDeleted() {
        bitField0_ = (bitField0_ & ~0x00000004);
        includeDeleted_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.protocol.resource.ListRequest)
    }

    static {
      defaultInstance = new ListRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.protocol.resource.ListRequest)
  }

  public interface ListResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.protocol.resource.ListResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKey schemaToken = 1;</code>
     */
    boolean hasSchemaToken();
    /**
     * <code>optional .io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKey schemaToken = 1;</code>
     */
    io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey getSchemaToken();
    /**
     * <code>optional .io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKey schemaToken = 1;</code>
     */
    io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKeyOrBuilder getSchemaTokenOrBuilder();

    /**
     * <code>repeated .io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.object.repgroup.ReplicationGroupInfo rgInfo = 2;</code>
     */
    java.util.List<io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfo> 
        getRgInfoList();
    /**
     * <code>repeated .io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.object.repgroup.ReplicationGroupInfo rgInfo = 2;</code>
     */
    io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfo getRgInfo(int index);
    /**
     * <code>repeated .io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.object.repgroup.ReplicationGroupInfo rgInfo = 2;</code>
     */
    int getRgInfoCount();
    /**
     * <code>repeated .io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.object.repgroup.ReplicationGroupInfo rgInfo = 2;</code>
     */
    java.util.List<? extends io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfoOrBuilder> 
        getRgInfoOrBuilderList();
    /**
     * <code>repeated .io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.object.repgroup.ReplicationGroupInfo rgInfo = 2;</code>
     */
    io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfoOrBuilder getRgInfoOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.protocol.resource.ListResponse}
   */
  public static final class ListResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.protocol.resource.ListResponse)
      ListResponseOrBuilder {
    // Use ListResponse.newBuilder() to construct.
    private ListResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ListResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ListResponse defaultInstance;
    public static ListResponse getDefaultInstance() {
      return defaultInstance;
    }

    public ListResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ListResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = schemaToken_.toBuilder();
              }
              schemaToken_ = input.readMessage(io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(schemaToken_);
                schemaToken_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                rgInfo_ = new java.util.ArrayList<io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfo>();
                mutable_bitField0_ |= 0x00000002;
              }
              rgInfo_.add(input.readMessage(io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfo.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          rgInfo_ = java.util.Collections.unmodifiableList(rgInfo_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.internal_static_io_pravega_segmentstore_storage_impl_chunkstream_storageos_data_protocol_resource_ListResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.internal_static_io_pravega_segmentstore_storage_impl_chunkstream_storageos_data_protocol_resource_ListResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListResponse.class, io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<ListResponse> PARSER =
        new com.google.protobuf.AbstractParser<ListResponse>() {
      public ListResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ListResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ListResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SCHEMATOKEN_FIELD_NUMBER = 1;
    private io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey schemaToken_;
    /**
     * <code>optional .io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKey schemaToken = 1;</code>
     */
    public boolean hasSchemaToken() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKey schemaToken = 1;</code>
     */
    public io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey getSchemaToken() {
      return schemaToken_;
    }
    /**
     * <code>optional .io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKey schemaToken = 1;</code>
     */
    public io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKeyOrBuilder getSchemaTokenOrBuilder() {
      return schemaToken_;
    }

    public static final int RGINFO_FIELD_NUMBER = 2;
    private java.util.List<io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfo> rgInfo_;
    /**
     * <code>repeated .io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.object.repgroup.ReplicationGroupInfo rgInfo = 2;</code>
     */
    public java.util.List<io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfo> getRgInfoList() {
      return rgInfo_;
    }
    /**
     * <code>repeated .io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.object.repgroup.ReplicationGroupInfo rgInfo = 2;</code>
     */
    public java.util.List<? extends io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfoOrBuilder> 
        getRgInfoOrBuilderList() {
      return rgInfo_;
    }
    /**
     * <code>repeated .io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.object.repgroup.ReplicationGroupInfo rgInfo = 2;</code>
     */
    public int getRgInfoCount() {
      return rgInfo_.size();
    }
    /**
     * <code>repeated .io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.object.repgroup.ReplicationGroupInfo rgInfo = 2;</code>
     */
    public io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfo getRgInfo(int index) {
      return rgInfo_.get(index);
    }
    /**
     * <code>repeated .io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.object.repgroup.ReplicationGroupInfo rgInfo = 2;</code>
     */
    public io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfoOrBuilder getRgInfoOrBuilder(
        int index) {
      return rgInfo_.get(index);
    }

    private void initFields() {
      schemaToken_ = io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey.getDefaultInstance();
      rgInfo_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasSchemaToken()) {
        if (!getSchemaToken().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getRgInfoCount(); i++) {
        if (!getRgInfo(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, schemaToken_);
      }
      for (int i = 0; i < rgInfo_.size(); i++) {
        output.writeMessage(2, rgInfo_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, schemaToken_);
      }
      for (int i = 0; i < rgInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, rgInfo_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.protocol.resource.ListResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.protocol.resource.ListResponse)
        io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.internal_static_io_pravega_segmentstore_storage_impl_chunkstream_storageos_data_protocol_resource_ListResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.internal_static_io_pravega_segmentstore_storage_impl_chunkstream_storageos_data_protocol_resource_ListResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListResponse.class, io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListResponse.Builder.class);
      }

      // Construct using io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSchemaTokenFieldBuilder();
          getRgInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (schemaTokenBuilder_ == null) {
          schemaToken_ = io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey.getDefaultInstance();
        } else {
          schemaTokenBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (rgInfoBuilder_ == null) {
          rgInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          rgInfoBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.internal_static_io_pravega_segmentstore_storage_impl_chunkstream_storageos_data_protocol_resource_ListResponse_descriptor;
      }

      public io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListResponse getDefaultInstanceForType() {
        return io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListResponse.getDefaultInstance();
      }

      public io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListResponse build() {
        io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListResponse buildPartial() {
        io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListResponse result = new io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (schemaTokenBuilder_ == null) {
          result.schemaToken_ = schemaToken_;
        } else {
          result.schemaToken_ = schemaTokenBuilder_.build();
        }
        if (rgInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            rgInfo_ = java.util.Collections.unmodifiableList(rgInfo_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.rgInfo_ = rgInfo_;
        } else {
          result.rgInfo_ = rgInfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListResponse) {
          return mergeFrom((io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListResponse other) {
        if (other == io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListResponse.getDefaultInstance()) return this;
        if (other.hasSchemaToken()) {
          mergeSchemaToken(other.getSchemaToken());
        }
        if (rgInfoBuilder_ == null) {
          if (!other.rgInfo_.isEmpty()) {
            if (rgInfo_.isEmpty()) {
              rgInfo_ = other.rgInfo_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureRgInfoIsMutable();
              rgInfo_.addAll(other.rgInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.rgInfo_.isEmpty()) {
            if (rgInfoBuilder_.isEmpty()) {
              rgInfoBuilder_.dispose();
              rgInfoBuilder_ = null;
              rgInfo_ = other.rgInfo_;
              bitField0_ = (bitField0_ & ~0x00000002);
              rgInfoBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRgInfoFieldBuilder() : null;
            } else {
              rgInfoBuilder_.addAllMessages(other.rgInfo_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasSchemaToken()) {
          if (!getSchemaToken().isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getRgInfoCount(); i++) {
          if (!getRgInfo(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.RGMessages.ListResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey schemaToken_ = io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey, io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey.Builder, io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKeyOrBuilder> schemaTokenBuilder_;
      /**
       * <code>optional .io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKey schemaToken = 1;</code>
       */
      public boolean hasSchemaToken() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKey schemaToken = 1;</code>
       */
      public io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey getSchemaToken() {
        if (schemaTokenBuilder_ == null) {
          return schemaToken_;
        } else {
          return schemaTokenBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKey schemaToken = 1;</code>
       */
      public Builder setSchemaToken(io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey value) {
        if (schemaTokenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          schemaToken_ = value;
          onChanged();
        } else {
          schemaTokenBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKey schemaToken = 1;</code>
       */
      public Builder setSchemaToken(
          io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey.Builder builderForValue) {
        if (schemaTokenBuilder_ == null) {
          schemaToken_ = builderForValue.build();
          onChanged();
        } else {
          schemaTokenBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKey schemaToken = 1;</code>
       */
      public Builder mergeSchemaToken(io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey value) {
        if (schemaTokenBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              schemaToken_ != io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey.getDefaultInstance()) {
            schemaToken_ =
              io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey.newBuilder(schemaToken_).mergeFrom(value).buildPartial();
          } else {
            schemaToken_ = value;
          }
          onChanged();
        } else {
          schemaTokenBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKey schemaToken = 1;</code>
       */
      public Builder clearSchemaToken() {
        if (schemaTokenBuilder_ == null) {
          schemaToken_ = io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey.getDefaultInstance();
          onChanged();
        } else {
          schemaTokenBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKey schemaToken = 1;</code>
       */
      public io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey.Builder getSchemaTokenBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getSchemaTokenFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKey schemaToken = 1;</code>
       */
      public io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKeyOrBuilder getSchemaTokenOrBuilder() {
        if (schemaTokenBuilder_ != null) {
          return schemaTokenBuilder_.getMessageOrBuilder();
        } else {
          return schemaToken_;
        }
      }
      /**
       * <code>optional .io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKey schemaToken = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey, io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey.Builder, io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKeyOrBuilder> 
          getSchemaTokenFieldBuilder() {
        if (schemaTokenBuilder_ == null) {
          schemaTokenBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey, io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKey.Builder, io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.SchemaKeyOrBuilder>(
                  getSchemaToken(),
                  getParentForChildren(),
                  isClean());
          schemaToken_ = null;
        }
        return schemaTokenBuilder_;
      }

      private java.util.List<io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfo> rgInfo_ =
        java.util.Collections.emptyList();
      private void ensureRgInfoIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          rgInfo_ = new java.util.ArrayList<io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfo>(rgInfo_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfo, io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfo.Builder, io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfoOrBuilder> rgInfoBuilder_;

      /**
       * <code>repeated .io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.object.repgroup.ReplicationGroupInfo rgInfo = 2;</code>
       */
      public java.util.List<io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfo> getRgInfoList() {
        if (rgInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(rgInfo_);
        } else {
          return rgInfoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.object.repgroup.ReplicationGroupInfo rgInfo = 2;</code>
       */
      public int getRgInfoCount() {
        if (rgInfoBuilder_ == null) {
          return rgInfo_.size();
        } else {
          return rgInfoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.object.repgroup.ReplicationGroupInfo rgInfo = 2;</code>
       */
      public io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfo getRgInfo(int index) {
        if (rgInfoBuilder_ == null) {
          return rgInfo_.get(index);
        } else {
          return rgInfoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.object.repgroup.ReplicationGroupInfo rgInfo = 2;</code>
       */
      public Builder setRgInfo(
          int index, io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfo value) {
        if (rgInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRgInfoIsMutable();
          rgInfo_.set(index, value);
          onChanged();
        } else {
          rgInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.object.repgroup.ReplicationGroupInfo rgInfo = 2;</code>
       */
      public Builder setRgInfo(
          int index, io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfo.Builder builderForValue) {
        if (rgInfoBuilder_ == null) {
          ensureRgInfoIsMutable();
          rgInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          rgInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.object.repgroup.ReplicationGroupInfo rgInfo = 2;</code>
       */
      public Builder addRgInfo(io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfo value) {
        if (rgInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRgInfoIsMutable();
          rgInfo_.add(value);
          onChanged();
        } else {
          rgInfoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.object.repgroup.ReplicationGroupInfo rgInfo = 2;</code>
       */
      public Builder addRgInfo(
          int index, io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfo value) {
        if (rgInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRgInfoIsMutable();
          rgInfo_.add(index, value);
          onChanged();
        } else {
          rgInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.object.repgroup.ReplicationGroupInfo rgInfo = 2;</code>
       */
      public Builder addRgInfo(
          io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfo.Builder builderForValue) {
        if (rgInfoBuilder_ == null) {
          ensureRgInfoIsMutable();
          rgInfo_.add(builderForValue.build());
          onChanged();
        } else {
          rgInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.object.repgroup.ReplicationGroupInfo rgInfo = 2;</code>
       */
      public Builder addRgInfo(
          int index, io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfo.Builder builderForValue) {
        if (rgInfoBuilder_ == null) {
          ensureRgInfoIsMutable();
          rgInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          rgInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.object.repgroup.ReplicationGroupInfo rgInfo = 2;</code>
       */
      public Builder addAllRgInfo(
          java.lang.Iterable<? extends io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfo> values) {
        if (rgInfoBuilder_ == null) {
          ensureRgInfoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, rgInfo_);
          onChanged();
        } else {
          rgInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.object.repgroup.ReplicationGroupInfo rgInfo = 2;</code>
       */
      public Builder clearRgInfo() {
        if (rgInfoBuilder_ == null) {
          rgInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          rgInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.object.repgroup.ReplicationGroupInfo rgInfo = 2;</code>
       */
      public Builder removeRgInfo(int index) {
        if (rgInfoBuilder_ == null) {
          ensureRgInfoIsMutable();
          rgInfo_.remove(index);
          onChanged();
        } else {
          rgInfoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.object.repgroup.ReplicationGroupInfo rgInfo = 2;</code>
       */
      public io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfo.Builder getRgInfoBuilder(
          int index) {
        return getRgInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.object.repgroup.ReplicationGroupInfo rgInfo = 2;</code>
       */
      public io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfoOrBuilder getRgInfoOrBuilder(
          int index) {
        if (rgInfoBuilder_ == null) {
          return rgInfo_.get(index);  } else {
          return rgInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.object.repgroup.ReplicationGroupInfo rgInfo = 2;</code>
       */
      public java.util.List<? extends io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfoOrBuilder> 
           getRgInfoOrBuilderList() {
        if (rgInfoBuilder_ != null) {
          return rgInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(rgInfo_);
        }
      }
      /**
       * <code>repeated .io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.object.repgroup.ReplicationGroupInfo rgInfo = 2;</code>
       */
      public io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfo.Builder addRgInfoBuilder() {
        return getRgInfoFieldBuilder().addBuilder(
            io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.object.repgroup.ReplicationGroupInfo rgInfo = 2;</code>
       */
      public io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfo.Builder addRgInfoBuilder(
          int index) {
        return getRgInfoFieldBuilder().addBuilder(
            index, io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.object.repgroup.ReplicationGroupInfo rgInfo = 2;</code>
       */
      public java.util.List<io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfo.Builder> 
           getRgInfoBuilderList() {
        return getRgInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfo, io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfo.Builder, io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfoOrBuilder> 
          getRgInfoFieldBuilder() {
        if (rgInfoBuilder_ == null) {
          rgInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfo, io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfo.Builder, io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.ReplicationGroupInfoOrBuilder>(
                  rgInfo_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          rgInfo_ = null;
        }
        return rgInfoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.protocol.resource.ListResponse)
    }

    static {
      defaultInstance = new ListResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.protocol.resource.ListResponse)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_pravega_segmentstore_storage_impl_chunkstream_storageos_data_protocol_resource_ListRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_pravega_segmentstore_storage_impl_chunkstream_storageos_data_protocol_resource_ListRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_pravega_segmentstore_storage_impl_chunkstream_storageos_data_protocol_resource_ListResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_pravega_segmentstore_storage_impl_chunkstream_storageos_data_protocol_resource_ListResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020RGMessages.proto\022Qio.pravega.segmentst" +
      "ore.storage.impl.chunkstream.storageos.d" +
      "ata.protocol.resource\032\026SchemaKeyRecords." +
      "proto\032\026ReplicationGroup.proto\032\nZone.prot" +
      "o\"\246\001\n\013ListRequest\022d\n\013schemaToken\030\001 \001(\0132O" +
      ".io.pravega.segmentstore.storage.impl.ch" +
      "unkstream.storageos.rpc.types.SchemaKey\022" +
      "\022\n\nmaxEntries\030\002 \001(\005\022\035\n\016includeDeleted\030\003 " +
      "\001(\010:\005false\"\353\001\n\014ListResponse\022d\n\013schemaTok" +
      "en\030\001 \001(\0132O.io.pravega.segmentstore.stora",
      "ge.impl.chunkstream.storageos.rpc.types." +
      "SchemaKey\022u\n\006rgInfo\030\002 \003(\0132e.io.pravega.s" +
      "egmentstore.storage.impl.chunkstream.sto" +
      "rageos.data.object.repgroup.ReplicationG" +
      "roupInfoBO\nAio.pravega.segmentstore.stor" +
      "age.impl.chunkstream.storageos.rpc.rgB\nR" +
      "GMessages"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.getDescriptor(),
          io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.getDescriptor(),
          io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.zone.Zone.getDescriptor(),
        }, assigner);
    internal_static_io_pravega_segmentstore_storage_impl_chunkstream_storageos_data_protocol_resource_ListRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_pravega_segmentstore_storage_impl_chunkstream_storageos_data_protocol_resource_ListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_pravega_segmentstore_storage_impl_chunkstream_storageos_data_protocol_resource_ListRequest_descriptor,
        new java.lang.String[] { "SchemaToken", "MaxEntries", "IncludeDeleted", });
    internal_static_io_pravega_segmentstore_storage_impl_chunkstream_storageos_data_protocol_resource_ListResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_pravega_segmentstore_storage_impl_chunkstream_storageos_data_protocol_resource_ListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_pravega_segmentstore_storage_impl_chunkstream_storageos_data_protocol_resource_ListResponse_descriptor,
        new java.lang.String[] { "SchemaToken", "RgInfo", });
    io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.types.SchemaKeyRecords.getDescriptor();
    io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.rg.ReplicationGroup.getDescriptor();
    io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.zone.Zone.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
