// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Zone.proto

package io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.zone;

public final class Zone {
  private Zone() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ZoneInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.object.zone.ZoneInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string vdcId = 1;</code>
     */
    boolean hasVdcId();
    /**
     * <code>required string vdcId = 1;</code>
     */
    java.lang.String getVdcId();
    /**
     * <code>required string vdcId = 1;</code>
     */
    com.google.protobuf.ByteString
        getVdcIdBytes();

    /**
     * <code>required string vdcName = 2;</code>
     */
    boolean hasVdcName();
    /**
     * <code>required string vdcName = 2;</code>
     */
    java.lang.String getVdcName();
    /**
     * <code>required string vdcName = 2;</code>
     */
    com.google.protobuf.ByteString
        getVdcNameBytes();

    /**
     * <code>required string dataEndPoints = 3;</code>
     */
    boolean hasDataEndPoints();
    /**
     * <code>required string dataEndPoints = 3;</code>
     */
    java.lang.String getDataEndPoints();
    /**
     * <code>required string dataEndPoints = 3;</code>
     */
    com.google.protobuf.ByteString
        getDataEndPointsBytes();

    /**
     * <code>required string cmdEndPoints = 4;</code>
     */
    boolean hasCmdEndPoints();
    /**
     * <code>required string cmdEndPoints = 4;</code>
     */
    java.lang.String getCmdEndPoints();
    /**
     * <code>required string cmdEndPoints = 4;</code>
     */
    com.google.protobuf.ByteString
        getCmdEndPointsBytes();

    /**
     * <code>required string secretKey = 5;</code>
     */
    boolean hasSecretKey();
    /**
     * <code>required string secretKey = 5;</code>
     */
    java.lang.String getSecretKey();
    /**
     * <code>required string secretKey = 5;</code>
     */
    com.google.protobuf.ByteString
        getSecretKeyBytes();

    /**
     * <code>optional string newSecretKey = 6;</code>
     */
    boolean hasNewSecretKey();
    /**
     * <code>optional string newSecretKey = 6;</code>
     */
    java.lang.String getNewSecretKey();
    /**
     * <code>optional string newSecretKey = 6;</code>
     */
    com.google.protobuf.ByteString
        getNewSecretKeyBytes();

    /**
     * <code>optional string managementEndPoints = 7;</code>
     *
     * <pre>
     *making this optional so that in upgrade envs there is no issue
     * </pre>
     */
    boolean hasManagementEndPoints();
    /**
     * <code>optional string managementEndPoints = 7;</code>
     *
     * <pre>
     *making this optional so that in upgrade envs there is no issue
     * </pre>
     */
    java.lang.String getManagementEndPoints();
    /**
     * <code>optional string managementEndPoints = 7;</code>
     *
     * <pre>
     *making this optional so that in upgrade envs there is no issue
     * </pre>
     */
    com.google.protobuf.ByteString
        getManagementEndPointsBytes();

    /**
     * <code>optional bool isHosted = 8;</code>
     */
    boolean hasIsHosted();
    /**
     * <code>optional bool isHosted = 8;</code>
     */
    boolean getIsHosted();
  }
  /**
   * Protobuf type {@code io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.object.zone.ZoneInfo}
   */
  public static final class ZoneInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.object.zone.ZoneInfo)
      ZoneInfoOrBuilder {
    // Use ZoneInfo.newBuilder() to construct.
    private ZoneInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ZoneInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ZoneInfo defaultInstance;
    public static ZoneInfo getDefaultInstance() {
      return defaultInstance;
    }

    public ZoneInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ZoneInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              vdcId_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              vdcName_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              dataEndPoints_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              cmdEndPoints_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              secretKey_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              newSecretKey_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              managementEndPoints_ = bs;
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              isHosted_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.zone.Zone.internal_static_io_pravega_segmentstore_storage_impl_chunkstream_storageos_data_object_zone_ZoneInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.zone.Zone.internal_static_io_pravega_segmentstore_storage_impl_chunkstream_storageos_data_object_zone_ZoneInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.zone.Zone.ZoneInfo.class, io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.zone.Zone.ZoneInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<ZoneInfo> PARSER =
        new com.google.protobuf.AbstractParser<ZoneInfo>() {
      public ZoneInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ZoneInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ZoneInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int VDCID_FIELD_NUMBER = 1;
    private java.lang.Object vdcId_;
    /**
     * <code>required string vdcId = 1;</code>
     */
    public boolean hasVdcId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string vdcId = 1;</code>
     */
    public java.lang.String getVdcId() {
      java.lang.Object ref = vdcId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          vdcId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string vdcId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getVdcIdBytes() {
      java.lang.Object ref = vdcId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vdcId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VDCNAME_FIELD_NUMBER = 2;
    private java.lang.Object vdcName_;
    /**
     * <code>required string vdcName = 2;</code>
     */
    public boolean hasVdcName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string vdcName = 2;</code>
     */
    public java.lang.String getVdcName() {
      java.lang.Object ref = vdcName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          vdcName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string vdcName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getVdcNameBytes() {
      java.lang.Object ref = vdcName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vdcName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATAENDPOINTS_FIELD_NUMBER = 3;
    private java.lang.Object dataEndPoints_;
    /**
     * <code>required string dataEndPoints = 3;</code>
     */
    public boolean hasDataEndPoints() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string dataEndPoints = 3;</code>
     */
    public java.lang.String getDataEndPoints() {
      java.lang.Object ref = dataEndPoints_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dataEndPoints_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string dataEndPoints = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDataEndPointsBytes() {
      java.lang.Object ref = dataEndPoints_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataEndPoints_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CMDENDPOINTS_FIELD_NUMBER = 4;
    private java.lang.Object cmdEndPoints_;
    /**
     * <code>required string cmdEndPoints = 4;</code>
     */
    public boolean hasCmdEndPoints() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string cmdEndPoints = 4;</code>
     */
    public java.lang.String getCmdEndPoints() {
      java.lang.Object ref = cmdEndPoints_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cmdEndPoints_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string cmdEndPoints = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCmdEndPointsBytes() {
      java.lang.Object ref = cmdEndPoints_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cmdEndPoints_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SECRETKEY_FIELD_NUMBER = 5;
    private java.lang.Object secretKey_;
    /**
     * <code>required string secretKey = 5;</code>
     */
    public boolean hasSecretKey() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string secretKey = 5;</code>
     */
    public java.lang.String getSecretKey() {
      java.lang.Object ref = secretKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          secretKey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string secretKey = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSecretKeyBytes() {
      java.lang.Object ref = secretKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        secretKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NEWSECRETKEY_FIELD_NUMBER = 6;
    private java.lang.Object newSecretKey_;
    /**
     * <code>optional string newSecretKey = 6;</code>
     */
    public boolean hasNewSecretKey() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string newSecretKey = 6;</code>
     */
    public java.lang.String getNewSecretKey() {
      java.lang.Object ref = newSecretKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          newSecretKey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string newSecretKey = 6;</code>
     */
    public com.google.protobuf.ByteString
        getNewSecretKeyBytes() {
      java.lang.Object ref = newSecretKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        newSecretKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MANAGEMENTENDPOINTS_FIELD_NUMBER = 7;
    private java.lang.Object managementEndPoints_;
    /**
     * <code>optional string managementEndPoints = 7;</code>
     *
     * <pre>
     *making this optional so that in upgrade envs there is no issue
     * </pre>
     */
    public boolean hasManagementEndPoints() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string managementEndPoints = 7;</code>
     *
     * <pre>
     *making this optional so that in upgrade envs there is no issue
     * </pre>
     */
    public java.lang.String getManagementEndPoints() {
      java.lang.Object ref = managementEndPoints_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          managementEndPoints_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string managementEndPoints = 7;</code>
     *
     * <pre>
     *making this optional so that in upgrade envs there is no issue
     * </pre>
     */
    public com.google.protobuf.ByteString
        getManagementEndPointsBytes() {
      java.lang.Object ref = managementEndPoints_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        managementEndPoints_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISHOSTED_FIELD_NUMBER = 8;
    private boolean isHosted_;
    /**
     * <code>optional bool isHosted = 8;</code>
     */
    public boolean hasIsHosted() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional bool isHosted = 8;</code>
     */
    public boolean getIsHosted() {
      return isHosted_;
    }

    private void initFields() {
      vdcId_ = "";
      vdcName_ = "";
      dataEndPoints_ = "";
      cmdEndPoints_ = "";
      secretKey_ = "";
      newSecretKey_ = "";
      managementEndPoints_ = "";
      isHosted_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasVdcId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVdcName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDataEndPoints()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCmdEndPoints()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSecretKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getVdcIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getVdcNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDataEndPointsBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getCmdEndPointsBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getSecretKeyBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getNewSecretKeyBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getManagementEndPointsBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBool(8, isHosted_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getVdcIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getVdcNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDataEndPointsBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getCmdEndPointsBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getSecretKeyBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getNewSecretKeyBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getManagementEndPointsBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, isHosted_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.zone.Zone.ZoneInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.zone.Zone.ZoneInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.zone.Zone.ZoneInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.zone.Zone.ZoneInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.zone.Zone.ZoneInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.zone.Zone.ZoneInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.zone.Zone.ZoneInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.zone.Zone.ZoneInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.zone.Zone.ZoneInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.zone.Zone.ZoneInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.zone.Zone.ZoneInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.object.zone.ZoneInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.object.zone.ZoneInfo)
        io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.zone.Zone.ZoneInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.zone.Zone.internal_static_io_pravega_segmentstore_storage_impl_chunkstream_storageos_data_object_zone_ZoneInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.zone.Zone.internal_static_io_pravega_segmentstore_storage_impl_chunkstream_storageos_data_object_zone_ZoneInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.zone.Zone.ZoneInfo.class, io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.zone.Zone.ZoneInfo.Builder.class);
      }

      // Construct using io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.zone.Zone.ZoneInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        vdcId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        vdcName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        dataEndPoints_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        cmdEndPoints_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        secretKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        newSecretKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        managementEndPoints_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        isHosted_ = false;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.zone.Zone.internal_static_io_pravega_segmentstore_storage_impl_chunkstream_storageos_data_object_zone_ZoneInfo_descriptor;
      }

      public io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.zone.Zone.ZoneInfo getDefaultInstanceForType() {
        return io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.zone.Zone.ZoneInfo.getDefaultInstance();
      }

      public io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.zone.Zone.ZoneInfo build() {
        io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.zone.Zone.ZoneInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.zone.Zone.ZoneInfo buildPartial() {
        io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.zone.Zone.ZoneInfo result = new io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.zone.Zone.ZoneInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.vdcId_ = vdcId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.vdcName_ = vdcName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.dataEndPoints_ = dataEndPoints_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.cmdEndPoints_ = cmdEndPoints_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.secretKey_ = secretKey_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.newSecretKey_ = newSecretKey_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.managementEndPoints_ = managementEndPoints_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.isHosted_ = isHosted_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.zone.Zone.ZoneInfo) {
          return mergeFrom((io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.zone.Zone.ZoneInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.zone.Zone.ZoneInfo other) {
        if (other == io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.zone.Zone.ZoneInfo.getDefaultInstance()) return this;
        if (other.hasVdcId()) {
          bitField0_ |= 0x00000001;
          vdcId_ = other.vdcId_;
          onChanged();
        }
        if (other.hasVdcName()) {
          bitField0_ |= 0x00000002;
          vdcName_ = other.vdcName_;
          onChanged();
        }
        if (other.hasDataEndPoints()) {
          bitField0_ |= 0x00000004;
          dataEndPoints_ = other.dataEndPoints_;
          onChanged();
        }
        if (other.hasCmdEndPoints()) {
          bitField0_ |= 0x00000008;
          cmdEndPoints_ = other.cmdEndPoints_;
          onChanged();
        }
        if (other.hasSecretKey()) {
          bitField0_ |= 0x00000010;
          secretKey_ = other.secretKey_;
          onChanged();
        }
        if (other.hasNewSecretKey()) {
          bitField0_ |= 0x00000020;
          newSecretKey_ = other.newSecretKey_;
          onChanged();
        }
        if (other.hasManagementEndPoints()) {
          bitField0_ |= 0x00000040;
          managementEndPoints_ = other.managementEndPoints_;
          onChanged();
        }
        if (other.hasIsHosted()) {
          setIsHosted(other.getIsHosted());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVdcId()) {
          
          return false;
        }
        if (!hasVdcName()) {
          
          return false;
        }
        if (!hasDataEndPoints()) {
          
          return false;
        }
        if (!hasCmdEndPoints()) {
          
          return false;
        }
        if (!hasSecretKey()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.zone.Zone.ZoneInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.pravega.segmentstore.storage.impl.chunkstream.storageos.rpc.zone.Zone.ZoneInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object vdcId_ = "";
      /**
       * <code>required string vdcId = 1;</code>
       */
      public boolean hasVdcId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string vdcId = 1;</code>
       */
      public java.lang.String getVdcId() {
        java.lang.Object ref = vdcId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            vdcId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string vdcId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getVdcIdBytes() {
        java.lang.Object ref = vdcId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          vdcId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string vdcId = 1;</code>
       */
      public Builder setVdcId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        vdcId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string vdcId = 1;</code>
       */
      public Builder clearVdcId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        vdcId_ = getDefaultInstance().getVdcId();
        onChanged();
        return this;
      }
      /**
       * <code>required string vdcId = 1;</code>
       */
      public Builder setVdcIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        vdcId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object vdcName_ = "";
      /**
       * <code>required string vdcName = 2;</code>
       */
      public boolean hasVdcName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string vdcName = 2;</code>
       */
      public java.lang.String getVdcName() {
        java.lang.Object ref = vdcName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            vdcName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string vdcName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getVdcNameBytes() {
        java.lang.Object ref = vdcName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          vdcName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string vdcName = 2;</code>
       */
      public Builder setVdcName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        vdcName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string vdcName = 2;</code>
       */
      public Builder clearVdcName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        vdcName_ = getDefaultInstance().getVdcName();
        onChanged();
        return this;
      }
      /**
       * <code>required string vdcName = 2;</code>
       */
      public Builder setVdcNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        vdcName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dataEndPoints_ = "";
      /**
       * <code>required string dataEndPoints = 3;</code>
       */
      public boolean hasDataEndPoints() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string dataEndPoints = 3;</code>
       */
      public java.lang.String getDataEndPoints() {
        java.lang.Object ref = dataEndPoints_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dataEndPoints_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string dataEndPoints = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDataEndPointsBytes() {
        java.lang.Object ref = dataEndPoints_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dataEndPoints_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string dataEndPoints = 3;</code>
       */
      public Builder setDataEndPoints(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        dataEndPoints_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string dataEndPoints = 3;</code>
       */
      public Builder clearDataEndPoints() {
        bitField0_ = (bitField0_ & ~0x00000004);
        dataEndPoints_ = getDefaultInstance().getDataEndPoints();
        onChanged();
        return this;
      }
      /**
       * <code>required string dataEndPoints = 3;</code>
       */
      public Builder setDataEndPointsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        dataEndPoints_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cmdEndPoints_ = "";
      /**
       * <code>required string cmdEndPoints = 4;</code>
       */
      public boolean hasCmdEndPoints() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string cmdEndPoints = 4;</code>
       */
      public java.lang.String getCmdEndPoints() {
        java.lang.Object ref = cmdEndPoints_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            cmdEndPoints_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string cmdEndPoints = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCmdEndPointsBytes() {
        java.lang.Object ref = cmdEndPoints_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cmdEndPoints_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string cmdEndPoints = 4;</code>
       */
      public Builder setCmdEndPoints(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        cmdEndPoints_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string cmdEndPoints = 4;</code>
       */
      public Builder clearCmdEndPoints() {
        bitField0_ = (bitField0_ & ~0x00000008);
        cmdEndPoints_ = getDefaultInstance().getCmdEndPoints();
        onChanged();
        return this;
      }
      /**
       * <code>required string cmdEndPoints = 4;</code>
       */
      public Builder setCmdEndPointsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        cmdEndPoints_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object secretKey_ = "";
      /**
       * <code>required string secretKey = 5;</code>
       */
      public boolean hasSecretKey() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string secretKey = 5;</code>
       */
      public java.lang.String getSecretKey() {
        java.lang.Object ref = secretKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            secretKey_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string secretKey = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSecretKeyBytes() {
        java.lang.Object ref = secretKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          secretKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string secretKey = 5;</code>
       */
      public Builder setSecretKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        secretKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string secretKey = 5;</code>
       */
      public Builder clearSecretKey() {
        bitField0_ = (bitField0_ & ~0x00000010);
        secretKey_ = getDefaultInstance().getSecretKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string secretKey = 5;</code>
       */
      public Builder setSecretKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        secretKey_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object newSecretKey_ = "";
      /**
       * <code>optional string newSecretKey = 6;</code>
       */
      public boolean hasNewSecretKey() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string newSecretKey = 6;</code>
       */
      public java.lang.String getNewSecretKey() {
        java.lang.Object ref = newSecretKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            newSecretKey_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string newSecretKey = 6;</code>
       */
      public com.google.protobuf.ByteString
          getNewSecretKeyBytes() {
        java.lang.Object ref = newSecretKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          newSecretKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string newSecretKey = 6;</code>
       */
      public Builder setNewSecretKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        newSecretKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string newSecretKey = 6;</code>
       */
      public Builder clearNewSecretKey() {
        bitField0_ = (bitField0_ & ~0x00000020);
        newSecretKey_ = getDefaultInstance().getNewSecretKey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string newSecretKey = 6;</code>
       */
      public Builder setNewSecretKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        newSecretKey_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object managementEndPoints_ = "";
      /**
       * <code>optional string managementEndPoints = 7;</code>
       *
       * <pre>
       *making this optional so that in upgrade envs there is no issue
       * </pre>
       */
      public boolean hasManagementEndPoints() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string managementEndPoints = 7;</code>
       *
       * <pre>
       *making this optional so that in upgrade envs there is no issue
       * </pre>
       */
      public java.lang.String getManagementEndPoints() {
        java.lang.Object ref = managementEndPoints_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            managementEndPoints_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string managementEndPoints = 7;</code>
       *
       * <pre>
       *making this optional so that in upgrade envs there is no issue
       * </pre>
       */
      public com.google.protobuf.ByteString
          getManagementEndPointsBytes() {
        java.lang.Object ref = managementEndPoints_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          managementEndPoints_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string managementEndPoints = 7;</code>
       *
       * <pre>
       *making this optional so that in upgrade envs there is no issue
       * </pre>
       */
      public Builder setManagementEndPoints(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        managementEndPoints_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string managementEndPoints = 7;</code>
       *
       * <pre>
       *making this optional so that in upgrade envs there is no issue
       * </pre>
       */
      public Builder clearManagementEndPoints() {
        bitField0_ = (bitField0_ & ~0x00000040);
        managementEndPoints_ = getDefaultInstance().getManagementEndPoints();
        onChanged();
        return this;
      }
      /**
       * <code>optional string managementEndPoints = 7;</code>
       *
       * <pre>
       *making this optional so that in upgrade envs there is no issue
       * </pre>
       */
      public Builder setManagementEndPointsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        managementEndPoints_ = value;
        onChanged();
        return this;
      }

      private boolean isHosted_ ;
      /**
       * <code>optional bool isHosted = 8;</code>
       */
      public boolean hasIsHosted() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional bool isHosted = 8;</code>
       */
      public boolean getIsHosted() {
        return isHosted_;
      }
      /**
       * <code>optional bool isHosted = 8;</code>
       */
      public Builder setIsHosted(boolean value) {
        bitField0_ |= 0x00000080;
        isHosted_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isHosted = 8;</code>
       */
      public Builder clearIsHosted() {
        bitField0_ = (bitField0_ & ~0x00000080);
        isHosted_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.object.zone.ZoneInfo)
    }

    static {
      defaultInstance = new ZoneInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:io.pravega.segmentstore.storage.impl.chunkstream.storageos.data.object.zone.ZoneInfo)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_pravega_segmentstore_storage_impl_chunkstream_storageos_data_object_zone_ZoneInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_pravega_segmentstore_storage_impl_chunkstream_storageos_data_object_zone_ZoneInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nZone.proto\022Kio.pravega.segmentstore.st" +
      "orage.impl.chunkstream.storageos.data.ob" +
      "ject.zone\"\257\001\n\010ZoneInfo\022\r\n\005vdcId\030\001 \002(\t\022\017\n" +
      "\007vdcName\030\002 \002(\t\022\025\n\rdataEndPoints\030\003 \002(\t\022\024\n" +
      "\014cmdEndPoints\030\004 \002(\t\022\021\n\tsecretKey\030\005 \002(\t\022\024" +
      "\n\014newSecretKey\030\006 \001(\t\022\033\n\023managementEndPoi" +
      "nts\030\007 \001(\t\022\020\n\010isHosted\030\010 \001(\010BE\nCio.praveg" +
      "a.segmentstore.storage.impl.chunkstream." +
      "storageos.rpc.zone"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_io_pravega_segmentstore_storage_impl_chunkstream_storageos_data_object_zone_ZoneInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_pravega_segmentstore_storage_impl_chunkstream_storageos_data_object_zone_ZoneInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_pravega_segmentstore_storage_impl_chunkstream_storageos_data_object_zone_ZoneInfo_descriptor,
        new java.lang.String[] { "VdcId", "VdcName", "DataEndPoints", "CmdEndPoints", "SecretKey", "NewSecretKey", "ManagementEndPoints", "IsHosted", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
